package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Vibrant Saffron / Orange (Bhagwa) / Red Theme
val md_theme_light_primary = Color(0xFFE65100) // Vibrant Saffron / Deep Orange
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC9)
val md_theme_light_onPrimaryContainer = Color(0xFF3B0A00)
val md_theme_light_secondary = Color(0xFFD32F2F) // Vibrant Red
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDADA)
val md_theme_light_onSecondaryContainer = Color(0xFF40000A)
val md_theme_light_tertiary = Color(0xFF725C00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE07D)
val md_theme_light_onTertiaryContainer = Color(0xFF231B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F6)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_surface = Color(0xFFFFF8F6)
val md_theme_light_onSurface = Color(0xFF201A18)

val md_theme_dark_primary = Color(0xFFFFB598)
val md_theme_dark_onPrimary = Color(0xFF651700)
val md_theme_dark_primaryContainer = Color(0xFF862400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC9)
val md_theme_dark_secondary = Color(0xFFFFB3B4)
val md_theme_dark_onSecondary = Color(0xFF680016)
val md_theme_dark_secondaryContainer = Color(0xFF920023)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADA)
val md_theme_dark_tertiary = Color(0xFFE4C349)
val md_theme_dark_onTertiary = Color(0xFF3C2F00)
val md_theme_dark_tertiaryContainer = Color(0xFF564500)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE07D)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DB)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DB)
